baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'MCM.LLC'

google_analytics_id: ""
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "36px"
footer:
  copyright_text: 'Established in 1990®.'

seo:
  meta_og_title: "Model Cargo Moovers LLC"
  meta_og_type: "website"
  meta_og_url: ""
  meta_og_image: ""
  meta_og_description: "Model Cargo Moovers, here to make shipping easier."
  meta_twitter_card: "summary"
  meta_twitter_site: "@CargoModel"
  meta_twitter_creator: "@CargoModel"

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
